name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate the Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: RKDLDE
          svg_out_path: github-contribution-grid-snake.svg

      - name: Create dist folder and move SVG
        run: |
          mkdir dist
          mv github-contribution-grid-snake.svg dist/

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
